# Generated by Django 2.2.12 on 2020-05-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padneb', '0002_auto_20200501_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='description',
        ),
    ]
