# Generated by Django 2.2.12 on 2020-05-04 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('padneb', '0004_auto_20200503_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='admission_date',
            field=models.DateField(verbose_name='Admitted on:'),
        ),
    ]
